name: Deploy Multi-Container App to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  EB_APPLICATION_NAME: kviz-portfolio
  EB_ENVIRONMENT_NAME: Kviz-portfolio-env

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::410293310465:role/github-kvizapp-role
          aws-region: ${{ env.AWS_REGION }}


      - name: Create ZIP deployment package
        run: zip -r deploy.zip . -x ".git/*"


      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          region: ${{ env.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
